name: bovino_vax
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  floor: ^1.4.2
  intl:
  window_manager: ^0.3.2
  sqflite: ^2.2.8+4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.12.0"
  floor_generator: ^1.4.2
  build_runner: ^2.1.2
  test:

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true